### ISSUE TITLE
Optimising graph initialisation time using while_loop

### ISSUE THREAD

**Issue by richardwth** [mandubian/neural-ode#3]
Many thanks for sharing your code. Following your code on custom gradients, I've implemented my version using TensorFlow 1.14 odeint in non-Eager mode. I departed from your batch-aware code which sets the first dimension of `da_t_dt`, `da_args_dargs`, `da_dvars` to be the batch size. When there are lots of parameters, I think this would result in huge memory cost. 

Now it seems my code is working fine on GPU. However, the first iteration (graph initialisation) always took exceptional long time (in both CPU and GPU modes) on a simple problem, which is to optimize the parameters in a general Lotka Volterra equation to fit the observations over a few hundred time steps. I think the issue is caused by repetitively adding the `for` loop in the `grad` function into the graph.

I have tried to replace the `for` loop in the `grad` function by `tf.while_loop`, but failed cluelessly. The main loop did run for a few hundred times but it seems the augmented ode function returned zero second derivatives for `ode_params`. The same code worked fine under `for` loop. 

Have you come across similar problem? Would you please provide any suggestion? Cheers.

**Comment by richardwth** [comment]
I found that this problem was caused by the undesired order of operations in `tf.while_loop` (see [this Github issue](https://github.com/tensorflow/tensorflow/issues/20639)) and can be fixed by adding `@tf.function` to the function defining the augmented ode: `a_gradient_aug`. Cheers.

**Comment by mandubian** [comment]
Hi, sorry for not answering to you earlier, I was away but you found the solution by yourself ;)
I must say it took me long time to make TF1.x version work and I had to switch to eager mode because TF gradient tape with multi-level embedded gradients were simply broken, doc was absent and tools to introspect what's happening very basic... at least in eager mode, I could make it work a bit...
